on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "${{ secrets['TOKEN'] }}" >> test.txt

      - name: Cat
        run: |
          cat test.txt